version: "2"

linters:
  enable:
    - govet
    - errcheck
    - ineffassign
    - unconvert
    - gocyclo
    - misspell
    - unparam
    - unused
    - gosec

formatters:
  enable:
    - gofmt

settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 3
    min-occurrences: 3

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
