version: "2"

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 3
    min-occurrences: 3

formatters:
  disable-all: true
  enable:
    - gofmt

linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - ineffassign
    - unconvert
    - gocyclo
    - misspell
    - unparam
    - unused
    - gosec

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
