version: "2"

formatters:
  enable:
    - gofmt

linters:
  enable:
    - govet
    - errcheck
    - ineffassign
    - unconvert
    - gocyclo
    - misspell
    - unparam
    - unused
    - gosec
  settings:
    govet:
      enable-all: true
      disable:
        - fieldalignment
    gocyclo:
      min-complexity: 25
    goconst:
      min-len: 3
      min-occurrences: 3

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
